apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-role-binding
  namespace: payments
subjects:
- kind: ServiceAccount
  name: default
  namespace: payments
roleRef:
  kind: Role
  name: reader-role
  apiGroup: rbac.authorization.k8s.io
