apiVersion: v1
kind: Service
metadata:
  name: {{ include "payments.name" . }}
spec:
  selector:
    group: {{ include "payments.name" . }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
