apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: payments-dr
  namespace: payments
spec:
  host: payments
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      http:
        http2MaxRequests: 1000
  subsets:
    - name: v1
      labels:
        app: payments-v1
    - name: v2
      labels:
        app: payments-v2
